name: CI

on:
   push:
      branches:
         - main
         - dev
   pull_request:
      branches:
         - main
         - dev

jobs:
   ci:
      runs-on: ubuntu-latest
      steps:
         -  name: Checkout
            uses: actions/checkout@v4.2.1

         -  name: Setup Node
            uses: actions/setup-node@v4
            with:
               node-version: "20"
               cache: yarn

         -  name: Restore cache
            uses: actions/cache@v4
            with:
               path: |
                  .next/cache
               # Generate a new cache whenever packages or source files change.
               key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
               # If source files changed but packages didn't, rebuild from a prior cache.
               restore-keys: |
                  ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}-

         -  name: Install dependencies
            run: yarn

         -  name: Lint types
            run: yarn lint:types

         -  name: Lint Next.js
            run: yarn lint:next
